from typing import List

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.const import UnitOfEnergy, PERCENTAGE, UnitOfPower, CURRENCY_DOLLAR, EntityCategory, UnitOfMass

from .entity import AlphaESSSensorDescription, AlphaESSButtonDescription, AlphaESSNumberDescription, AlphaESSTimeDescription
from .enums import AlphaESSNames

FULL_SENSOR_DESCRIPTIONS: List[AlphaESSSensorDescription] = [
    AlphaESSSensorDescription(
        key=AlphaESSNames.SolarProduction,
        name="Solar Production",
        icon="mdi:solar-power",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.SolarToBattery,
        name="Solar to Battery",
        icon="mdi:battery-arrow-up",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.SolarToGrid,
        name="Solar to Grid",
        icon="mdi:transmission-tower-export",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.SolarToLoad,
        name="Solar to Load",
        icon="mdi:solar-power",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.TotalLoad,
        name="Total Load",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.GridToLoad,
        name="Grid to Load",
        icon="mdi:transmission-tower-import",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.GridToBattery,
        name="Grid to Battery",
        icon="mdi:battery-arrow-down",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Charge,
        name="Charge",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Discharge,
        name="Discharge",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.EVCharger,
        name="EV Charger",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Generation,
        name="Instantaneous Generation",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PPV1,
        name="Instantaneous PPV1",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PPV2,
        name="Instantaneous PPV2",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PPV3,
        name="Instantaneous PPV3",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PPV4,
        name="Instantaneous PPV4",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.GridIOL1,
        name="Instantaneous Grid I/O L1",
        icon="mdi:transmission-tower",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.GridIOL2,
        name="Instantaneous Grid I/O L2",
        icon="mdi:transmission-tower",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.GridIOL3,
        name="Instantaneous Grid I/O L3",
        icon="mdi:transmission-tower",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.BatterySOC,
        name="Instantaneous Battery SOC",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.BatteryIO,
        name="Instantaneous Battery I/O",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.GridIOTotal,
        name="Instantaneous Grid I/O Total",
        icon="mdi:transmission-tower",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Load,
        name="Instantaneous Load",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Total_Generation,
        name="Total Generation",
        icon="mdi:solar-power-variant",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Income,
        name="Total Income",
        icon="mdi:cash-multiple",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.SelfConsumption,
        name="Self Consumption",
        icon="mdi:home-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.SelfSufficiency,
        name="Self Sufficiency",
        icon="mdi:home-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.EmsStatus,
        name="EMS Status",
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.ENUM,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.usCapacity,
        name="Maximum Battery Capacity",
        icon="mdi:home-percent",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.TOTAL,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.cobat,
        name="Installed Capacity",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL,
        device_class=SensorDeviceClass.ENERGY,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.surplusCobat,
        name="Current Capacity",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL,
        device_class=SensorDeviceClass.ENERGY,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ChargeTime1,
        name="Charge Time 1",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:clock-time-ten",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ChargeTime2,
        name="Charge Time 2",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:clock-time-ten",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.DischargeTime1,
        name="Discharge Time 1",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:clock-time-ten",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.DischargeTime2,
        name="Discharge Time 2",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:clock-time-ten",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ChargeRange,
        name="Charging Range",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-lock-open",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.mbat,
        name="Battery Model",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart-variant",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.poinv,
        name="Inverter nominal Power",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL,
        device_class=SensorDeviceClass.ENERGY,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:lightning-bolt",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.popv,
        name="Pv nominal Power",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL,
        device_class=SensorDeviceClass.ENERGY,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:lightning-bolt",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.pmeterDc,
        name="pmeterDc",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ElectricVehiclePowerOne,
        name="Electric Vehicle Power One",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-electric",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ElectricVehiclePowerTwo,
        name="Electric Vehicle Power Two",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-electric",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ElectricVehiclePowerThree,
        name="Electric Vehicle Power Three",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-electric",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ElectricVehiclePowerFour,
        name="Electric Vehicle Power Four",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-electric",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.pev,
        name="pev",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PrealL1,
        name="PrealL1",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PrealL2,
        name="PrealL2",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PrealL3,
        name="PrealL3",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.carbonReduction,
        name="Co2 Reduction",
        native_unit_of_measurement=UnitOfMass.KILOGRAMS,
        device_class=SensorDeviceClass.WEIGHT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:molecule-co2",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.treePlanted,
        name="Trees Planted",
        native_unit_of_measurement=None,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:tree",
    )
]

LIMITED_SENSOR_DESCRIPTIONS: List[AlphaESSSensorDescription] = [
    AlphaESSSensorDescription(
        key=AlphaESSNames.StateOfCharge,
        name="State of Charge",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.SolarProduction,
        name="Solar Production",
        icon="mdi:solar-power",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.SolarToBattery,
        name="Solar to Battery",
        icon="mdi:battery-arrow-up",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.TotalLoad,
        name="Total Load",
        icon="mdi:home-lightning-bolt",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.GridToLoad,
        name="Grid to Load",
        icon="mdi:transmission-tower-import",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.GridToBattery,
        name="Grid to Battery",
        icon="mdi:battery-arrow-down",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Charge,
        name="Charge",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Discharge,
        name="Discharge",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.EVCharger,
        name="EV Charger",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.GridIOTotal,
        name="Instantaneous Grid I/O Total",
        icon="mdi:transmission-tower",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Load,
        name="Instantaneous Load",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Total_Generation,
        name="Total Generation",
        icon="mdi:solar-power-variant",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.Income,
        name="Total Income",
        icon="mdi:cash-multiple",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.SelfConsumption,
        name="Self Consumption",
        icon="mdi:home-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.SelfSufficiency,
        name="Self Sufficiency",
        icon="mdi:home-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.EmsStatus,
        name="EMS Status",
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.ENUM,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.usCapacity,
        name="Maximum Battery Capacity",
        icon="mdi:battery-high",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.TOTAL,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.cobat,
        name="Installed Capacity",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL,
        device_class=SensorDeviceClass.ENERGY,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.surplusCobat,
        name="Current Capacity",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL,
        device_class=SensorDeviceClass.ENERGY,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ChargeTime1,
        name="Charge Time 1",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:clock-time-ten",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ChargeTime2,
        name="Charge Time 2",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:clock-time-ten",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.DischargeTime1,
        name="Discharge Time 1",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:clock-time-ten",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.DischargeTime2,
        name="Discharge Time 2",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:clock-time-ten",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ChargeRange,
        name="Charging Range",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-lock-open",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.mbat,
        name="Battery Model",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:battery-heart-variant",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.poinv,
        name="Inverter nominal Power",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=None,
        device_class=SensorDeviceClass.ENERGY,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:lightning-bolt",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.popv,
        name="Pv nominal Power",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=None,
        device_class=SensorDeviceClass.ENERGY,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:lightning-bolt",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.pmeterDc,
        name="pmeterDc",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ElectricVehiclePowerOne,
        name="Electric Vehicle Power One",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-electric",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ElectricVehiclePowerTwo,
        name="Electric Vehicle Power Two",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-electric",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ElectricVehiclePowerThree,
        name="Electric Vehicle Power Three",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-electric",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ElectricVehiclePowerFour,
        name="Electric Vehicle Power Four",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-electric",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.pev,
        name="pev",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PrealL1,
        name="PrealL1",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PrealL2,
        name="PrealL2",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.PrealL3,
        name="PrealL3",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.carbonReduction,
        name="Carbon Reduction",
        native_unit_of_measurement=UnitOfMass.KILOGRAMS,
        device_class=SensorDeviceClass.WEIGHT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:molecule-co2",
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.treePlanted,
        name="Trees Planted",
        native_unit_of_measurement=None,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:tree",
    )
]

SUPPORT_DISCHARGE_AND_CHARGE_BUTTON_DESCRIPTIONS: List[AlphaESSButtonDescription] = [
    AlphaESSButtonDescription(
        key=AlphaESSNames.ButtonDischargeFifteen,
        name="15 Minute Discharge",
        icon="mdi:battery-negative",
        entity_category=EntityCategory.CONFIG,
    ),
    AlphaESSButtonDescription(
        key=AlphaESSNames.ButtonDischargeThirty,
        name="30 Minute Discharge",
        icon="mdi:battery-negative",
        entity_category=EntityCategory.CONFIG,
    ),
    AlphaESSButtonDescription(
        key=AlphaESSNames.ButtonDischargeSixty,
        name="60 Minute Discharge",
        icon="mdi:battery-negative",
        entity_category=EntityCategory.CONFIG,
    ),
    AlphaESSButtonDescription(
        key=AlphaESSNames.ButtonChargeFifteen,
        name="15 Minute Charge",
        icon="mdi:battery-positive",
        entity_category=EntityCategory.CONFIG,
    ),
    AlphaESSButtonDescription(
        key=AlphaESSNames.ButtonChargeThirty,
        name="30 Minute Charge",
        icon="mdi:battery-positive",
        entity_category=EntityCategory.CONFIG,
    ),
    AlphaESSButtonDescription(
        key=AlphaESSNames.ButtonChargeSixty,
        name="60 Minute Charge",
        icon="mdi:battery-positive",
        entity_category=EntityCategory.CONFIG,
    ),
    AlphaESSButtonDescription(
        key=AlphaESSNames.ButtonRechargeConfig,
        name="Reset Charge/Discharge",
        icon="mdi:battery-off",
        entity_category=EntityCategory.CONFIG,
    )
]

DISCHARGE_AND_CHARGE_NUMBERS: List[AlphaESSNumberDescription] = [
    AlphaESSNumberDescription(
        key=AlphaESSNames.batHighCap,
        name="batHighCap",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-sync",
        native_unit_of_measurement=PERCENTAGE,

    ),
    AlphaESSNumberDescription(
        key=AlphaESSNames.batUseCap,
        name="batUseCap",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-sync",
        native_unit_of_measurement=PERCENTAGE,
    )
]

CHARGE_DISCHARGE_TIMES: List[AlphaESSTimeDescription] = [
    AlphaESSTimeDescription(
        key=AlphaESSNames.ChargeStartTime1,
        name="Charge Start Time 1",
        icon="mdi:clock-start",
        entity_category=EntityCategory.CONFIG,
        coordinator_key="charge_timeChaf1",
    ),
    AlphaESSTimeDescription(
        key=AlphaESSNames.ChargeEndTime1,
        name="Charge End Time 1",
        icon="mdi:clock-end",
        entity_category=EntityCategory.CONFIG,
        coordinator_key="charge_timeChae1",
    ),
    AlphaESSTimeDescription(
        key=AlphaESSNames.ChargeStartTime2,
        name="Charge Start Time 2",
        icon="mdi:clock-start",
        entity_category=EntityCategory.CONFIG,
        coordinator_key="charge_timeChaf2",
    ),
    AlphaESSTimeDescription(
        key=AlphaESSNames.ChargeEndTime2,
        name="Charge End Time 2",
        icon="mdi:clock-end",
        entity_category=EntityCategory.CONFIG,
        coordinator_key="charge_timeChae2",
    ),
    AlphaESSTimeDescription(
        key=AlphaESSNames.DischargeStartTime1,
        name="Discharge Start Time 1",
        icon="mdi:clock-start",
        entity_category=EntityCategory.CONFIG,
        coordinator_key="discharge_timeDisf1",
    ),
    AlphaESSTimeDescription(
        key=AlphaESSNames.DischargeEndTime1,
        name="Discharge End Time 1",
        icon="mdi:clock-end",
        entity_category=EntityCategory.CONFIG,
        coordinator_key="discharge_timeDise1",
    ),
    AlphaESSTimeDescription(
        key=AlphaESSNames.DischargeStartTime2,
        name="Discharge Start Time 2",
        icon="mdi:clock-start",
        entity_category=EntityCategory.CONFIG,
        coordinator_key="discharge_timeDisf2",
    ),
    AlphaESSTimeDescription(
        key=AlphaESSNames.DischargeEndTime2,
        name="Discharge End Time 2",
        icon="mdi:clock-end",
        entity_category=EntityCategory.CONFIG,
        coordinator_key="discharge_timeDise2",
    ),
]

EV_DISCHARGE_AND_CHARGE_BUTTONS: List[AlphaESSNumberDescription] = [

    AlphaESSButtonDescription(
        key=AlphaESSNames.stopcharging,
        name="Stop Charging",
        icon="mdi:battery-off",
        entity_category=EntityCategory.CONFIG,
    ),
    AlphaESSButtonDescription(
        key=AlphaESSNames.startcharging,
        name="Start Charging",
        icon="mdi:battery-plus",
        entity_category=EntityCategory.CONFIG,
    )

]

LOCAL_IP_SYSTEM_SENSORS: List[AlphaESSSensorDescription] = [
    AlphaESSSensorDescription(
        key=AlphaESSNames.localIP,
        name="Local IP",
        icon="mdi:ip-network",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.wifiStatus,
        name="WiFi Status",
        icon="mdi:wifi",
        device_class=SensorDeviceClass.ENUM,
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.connectedSSID,
        name="Connected SSID",
        icon="mdi:wifi-marker",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.softwareVersion,
        name="Software Version",
        icon="mdi:package-variant",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.hardwareVersion,
        name="Hardware Version",
        icon="mdi:chip",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.deviceSerialNumber,
        name="Device Serial Number",
        icon="mdi:identifier",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.cloudConnectionStatus,
        name="Cloud Connection Status",
        icon="mdi:cloud-sync",
        device_class=SensorDeviceClass.ENUM,
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.ethernetModule,
        name="Ethernet Status",
        device_class=SensorDeviceClass.ENUM,
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:ethernet"
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.fourGModule,
        name="4G Status",
        device_class=SensorDeviceClass.ENUM,
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:signal-4g"
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.registerKey,
        name="Register Key",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:key"
    ),
]

EV_CHARGING_DETAILS: List[AlphaESSSensorDescription] = [
    AlphaESSSensorDescription(
        key=AlphaESSNames.evchargersn,
        name="EV Charger S/N",
        icon="mdi:ev-station",
        native_unit_of_measurement=None,
        state_class=None,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.evchargermodel,
        name="EV Charger Model",
        icon="mdi:ev-station",
        native_unit_of_measurement=None,
        state_class=None,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.evchargerstatusraw,
        name="EV Charger Status Raw",
        icon="mdi:ev-station",
        native_unit_of_measurement=None,
        state_class=None,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.evchargerstatus,
        name="EV Charger Status",
        icon="mdi:ev-station",
        device_class="enum",
        native_unit_of_measurement=None,
        state_class=None,
    ),
    AlphaESSSensorDescription(
        key=AlphaESSNames.evcurrentsetting,
        name="Household current setup",
        icon="mdi:ev-station",
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement="A",
        state_class=None,
    )

]
